### PR TITLE
visionmedia debug wrapper

### PR DESCRIPTION
**Pull request by nmccready**
@zacronos please review

### CODE REVIEW

**Comment by nmccready** [comment]
resolves issue #4

**Comment by nmccready** [comment]
@zacronos here it is in action http://plnkr.co/edit/qYtbwIXDWaurffr85qyi

**Comment by zacronos** [comment]
Are `dist/index.js` and `dist/angular-simple-logger.js` the same thing?  And `dist/index.light.js` with `dist/angular-simple-logger.light.js`?

If so, why the redundancy?

**Comment by nmccready** [comment]
It is because thats how I started the project as index.js only. The redundancy is to not break other people's old code. The request for angular-simple-logger.js was made later.

**Comment by nmccready** [comment]
@zacronos #2

**Comment by zacronos** [comment]
Gotcha.  LGTM, nice work.

**Comment by nmccready** [comment]
cool

**Pull request merged**
